services:
  app:
    image: lucasmartins1508/restaurante:staging
    container_name: restaurante-lucas-martins
    restart: unless-stopped
    ports:
      - "8083:3000"
    environment:
      DB_HOST: mysql-infra
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: lucasmartdb
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - rede_alunos
networks:
  rede_alunos:
    external: true
